#!lua

--[[
Title: action

The action library is used to create actions that can be run by nodes. These actions can change the nodes
properties over time, e.g., position, rotation, animating a sprite. The actions can be chained together
to form sequences or run in parallel.
]]


--[[
  	Function: action.rotate
  	Creates an action to rotate a <Node>.
  
  	Parameters:
		angle - The angle by which to rotate the target Node
		duration - The duration of the action
		
  	Returns:
		The created Action.
   
]]

--[[
	Function: action.moveToX
	Create an action that causes the target <Node> to change its x-coordinate to a new value in some time interval.

	Parameters:
	  x - The x-coordinate value.
	  duration - The time over which the <Node> should move from it's current x value to the new one.
]]


--[[
	Function: action.followPath
	Create an action that causes the target <Node> to move along a 
	given <Path>.
	
	Parameters:
		path - A <Path> object that the target <Node> will follow
		duration - The duration of the action
		asOffset - An optional boolean indicating whether or not the path is offset from the Node location (default false)
		orientToPath - An optional boolean indicating whether or not the Node turns with the path (default false)

]]

--[[
	Function: action.animate
	Create an action that animates a <Sprite>.
	
	Parameters:
	  textures - One or more textures to be used as the frames of the animation.
	  frameDuration - The duration of each frame in seconds.
]]


--[[
	Function: action.repeatAction
	Exectues an action repeatedly.
	
	Parameters:
		action - The action to be repeated.
		repeat_count - The number of times to repeat the action - values less than or equal to zero mean repeat forever.

]]
