#!lua

--[[
Title: director

The director library provides scene manageement, with methods to load, initialize, transition to, and destroy
scenes.
]]

--[[
		Function: director.newScene
		Creates an empty scene. This method should be called from a scene module before other initialization.
		See the <Scene Template>.

		Parameters:
		none

		Returns:
		An empty scene.
]]

--[[
  	Function: director.loadScene
  	Loads a scene but doesn't display it yet.  The createScene method will be called on the scene.  Any textures created in this method call are loaded in a background thread.
  
  	Parameters:
		file - The name of the file to load.

  	Returns:
		The created scene.
  
  	See Also:
		<director.gotoScene>
]]
function director.loadScene( file, param1, param2 )
end

--[[
	Function: director.gotoScene
	Transitions to a scene.  The scene is loaded if it has not already
	been.
	
	Parameters:
		scene - the name of the scene
		params - an optional table specifying the transition to use and the parameters of that transition

	See Also:
		<director.loadScene> 
]]
function director.gotoScene( sceneName, params )
end


