#!lua

local node = {}

--[[
  	Function: function node.newBezierPath(x0, y0, x1, y1, a0x, a0y [,...] )
  	Creates a Bezier Path.
  
  	Parameters:
		x0 - the x-coordinate of the first point on the path
		y0 - the y-coordinate of the second point on the path, x1, y1, a0x, a0y
		x1 - the x-coordinate of the second point on the path
		y1 - the y-coordinate of the second point on the path
		a0x - the x-coordinate of the first anchor point
		a0y - the y-coordinate of the second anchor point

  	Returns:
		The created Path.
  
 
]]
function node.newBezierPath(x0, y0, x1, y1, a0x, a0y, ... , xn, yn, anx, any)
end


return node