#!lua
local shape = {}

--[[
Title: shape

The shape library provides methods to create shapes likes rectancgles, polygons, circles, and bezier curves.
]]

--[[
  	Function: shape.newRect
  	Creates a rectangle.
  
  	Parameters:
		x - The x coordinate of the center of the rectangle
		y - The y coordinate of the center of the rectangle
		width - The width of the rectangle
		height - The height of the rectangle

  	Returns:
		The created rectangle.
  
  	See Also:
		<rectangle>
]]
function shape.newRect( x, y, width, height )
end

--[[
	Function: shape.newCircle
	Create a circle.
	
	Parameters:
		x - The x coordinate of the center of the circle
		y - The y coordinate of the center of the circle
		radius - The radius of the circle

	See Also:
		<circle> 
]]
function shape.newCircle( x1, y1, radius )
end

--[[
	Function: shape.newCurve
	Create a curve based on a <BezierPath>.
	
	Parameters:
		path - A Bezier path crated with <path.newBezierPath>.

	See Also:
		<BezierCurve><BezierPath> 
]]
function shape.newCurve( path )
end

return shape